### ISSUE TITLE
feature: dynamic topic filtering routing with wildcards

### ISSUE THREAD

**Issue by dilbertside** [ralscha/wampspring#3]
I'm thinking about a scenario I'm going to need in the near future.

newsfeed scenario is:

I have multiple clients interested on some general news topic such as

1 client subscribe to following
newsagency.politics.asia.thailand
another client subscribe
newsagency.politics.asia.cambodia

where another would like, let's say subscribe to all
newsagency.politics.asia.*
or
newsagency.*.asia.singapore

NB: separator is ".", but could be "/" or else except ":" used by prefix curie

This a classic in EAI patterns
	http://www.eaipatterns.com/MessageRouter.html
	http://www.eaipatterns.com/Filter.html
	
I exclude content routing, it is out of scope in this library, better use Spring Integration.

What I foresee is more destination topic routing.
First served would be the full topic subscriber, where after wildcard subscribers would be processed

I guess @WampPublishListener, @WampSubscribeListener, @WampCallListener should include a regex, or wildcard switch to activate destination pattern.
separator could be a general configuration or a case by case setup.

To avoid a performance drop for current simple destination,
PubSubHandler should have an additional method like sendToMatchingTopic which will search for matching destinations/topics
example:
eventMessenger.sendToMatchingTopic("newsagency.politics.asia.*", list);

I wonder if SpEL expression evaluation could be of any use.
SpEL can use regex, or build a graph of destinations will be better (http://introcs.cs.princeton.edu/java/45graph/, http://jgrapht.org/)

Would you see this feature a valuable addition to implement? 

reference: https://en.wikipedia.org/wiki/Publish%E2%80%93subscribe_pattern#Message_filtering

**Comment by ralscha** [comment]
Wildcards are now supported in the 1.1.0 release. Works similar to the built in stomp support in the Spring Framework. It uses the AntPathMatcher class to match destinations with wildcards.
